67239 - Add status hints as input + README

diff --git a/send_slack_message_deployment/action.yml b/send_slack_message_deployment/action.yml
--- a/send_slack_message_deployment/action.yml
+++ b/send_slack_message_deployment/action.yml
@@ -5,16 +5,19 @@ inputs:
   status:
     description: Status to be notified. It can be either 'success' or 'failure'
     required: true
+  status-hint-success:
+    description: A hint to display if the status is `success`.
+    required: false
+  status-hint-failure:
+    description: A hint to display if the status is `failure`.
+    required: false
+    default: "Check the AWS logs during ECS deployment"
   template-file-path:
     description: Path to the template containing message payload JSON according to the BlockKit specification (https://api.slack.com/block-kit/building)
     required: false
   slack-webhook-url:
     description: URL of the Slack webhook to send the notification
     required: true
-
-outputs: 
-  SLACK_MESSAGE:
-    description: Generated slack message to send
 
 runs:
   using: 'composite'
@@ -23,9 +26,10 @@ runs:
       shell: bash
       run: |
         echo "RUN_LINK=https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID" >> $GITHUB_ENV
+        echo "COMMIT_FORMATTED=$(git log -1 --oneline --pretty=format:'%s' | sed 's/"/\\"/g')" >> $GITHUB_ENV
         echo "DEPLOYMENT_STATUS=$(echo "${{ inputs.status }}" | tr '[:lower:]' '[:upper:]')" >> $GITHUB_ENV
         echo "DEPLOYMENT_STATUS_ICON=$([ "${{ inputs.status }}" == "success" ] && echo "https://www.iconsdb.com/icons/download/green/check-mark-11-128.gif" || echo "https://www.iconsdb.com/icons/download/red/warning-3-128.jpg")" >> $GITHUB_ENV
-        echo "DEPLOYMENT_STATUS_HINT=$([ "${{ inputs.status }}" == "success" ] && echo "This is a regular release. See the latest release changelog" || echo "Check the AWS logs during ECS deployment")" >> $GITHUB_ENV
+        echo "DEPLOYMENT_STATUS_HINT=$([ "${{ inputs.status }}" == "success" ] && echo "${{ inputs.status-hint-success }}" || echo "${{ inputs.status-hint-failure }}")" >> $GITHUB_ENV
     - name: Substitute variables in the slack message template
       uses: danielr1996/envsubst-action@1.1.0
       with:
